import "./globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";
import Navegation from "../components/navigator";
import Footer from "../components/footer";
import { CartProvider, useCart } from "@/context/CartContext";
//import { AuthProvider } from "@/context/AuthContext";

import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative flex flex-col justify-between antialiased min-h-screen bg-background ">
        <div className="flex flex-col justify-start items-center w-full">
          <SessionProvider>
            <CartProvider>
              <Navegation />
              {children}
            </CartProvider>
          </SessionProvider>
        </div>
        <div className="flex items-end w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}